<!doctype html>
<html lang="en">
<head>
    <title>Test task for Intetics</title>
</head>
<body>
    <div>
        <h1>Enter and submit text</h1>
        <form action="/" method="post">
            <div>
                <input type="hidden" name="csrf" value="<?=$csrf?>">
                <textarea
                        name="textarea"
                        placeholder="<?=htmlspecialchars($placeholder)?>"
                        rows="10"
                        cols="50"
                ><?=htmlspecialchars($value)?></textarea>
            </div>
            <?php if ($error !== '') : ?>
            <div>
                <?=htmlspecialchars($error)?>
            </div>
            <?php endif; ?>
            <div>
                <input type="submit">
            </div>
        </form>
    </div>
</body>
</html>