<!doctype html>
<html lang="en">
<head>
    <title>Test task for Intetics</title>
</head>
<body>
    <div>
        <h1>Enter and submit text</h1>
        <form action="/" method="post">
            <div>
                <textarea
                        name="textarea"
                        placeholder="<?=$placeholder?>"
                        rows="10"
                        cols="50"
                ><?=$value?></textarea>
            </div>
            <?php if ($error !== '') : ?>
            <div>
                <?=$error?>
            </div>
            <?php endif; ?>
            <div>
                <input type="submit">
            </div>
        </form>
    </div>
</body>
</html>